.TH "DPViewergtk" "1" "0.0.1" "Tiago C. Teixeira" "Applications/Education"
.SH "NAME"
.LP 
\fBDPViewergtk\fR
 \- Software design patterns viewer
.SH "SYNOPSIS"
.LP 
.TP 
\fB./DPViewergtk [options]\fR
To run from the command prompt.
.TP 
\fBApplications menu/Education/DPViewergtk\fR
To run from graphics environment.
.SH "DESCRIPTION"
.LP 
This is a GUI application that allows you to view information about software design patterns.
From a list of software design patterns you can view the description of the pattern, a code example, its frequency of use, the participant entities and real world usage case examples in a single window.
.SH "OPTIONS"
.LP 
.TP 
\fB\-v, \-\-version\fR
Display version information and exit.

.TP 
\fB\-h, \-\-help\fR
Display help message and exit.
.SH "FILES"
.LP 
Assuming the application is installed with the default prefix '/usr/'
.br 
\fI\fP
.br 
\fI/usr/bin/DPViewergtk\fP 
.br 
\fI/var/DPViewergtk/database/dpviewerdb.sqlite\fP 
.br 
\fI/usr/share/applications/DPViewergtk.desktop\fP 
.br 
\fI/usr/share/DPViewergtk/images/logo.svg\fP 
.br 
\fI/usr/share/doc/DPViewergtk/AUTHORS\fP 
.br 
\fI/usr/share/doc/DPViewergtk/ChangeLog\fP 
.br 
\fI/usr/share/doc/DPViewergtk/README\fP 
.br 
\fI/usr/share/icons/hicolor/scalable/apps/DPViewergtk.svg\fP
.br 
\fI/usr/share/licenses/DPViewergtk/COPYING\fP
.br 
\fI/usr/share/man/man1/DPViewergtk.1.gz\fP
.br 
\fI/usr/share/locale/pt/LC_MESSAGES/DPViewergtk.mo
\fP

.SH "EXAMPLES"
.LP 
.TP 
\fB./DPViewergtk\fR
To run this program the standard way from the command prompt.

.TP 
\fBApplications menu/Education/DPViewergtk\fR
To run from the graphical enviroment.

.TP 
\fB./DPViewergtk \-v\fR
To display version information and exit.

.TP 
\fB./DPViewergtk \-h\fR
To display help information and exit.
.SH "RESOURCES"
.LP 
.TP 
* GitHub: https://github.com/tclsteixeira/design\-patterns\-viewer


.SH "AUTHORS"
.LP 
Tiago C. Teixeira <tclstdev@gmail.com>
