/*
 * sql.h
 *
 *  Created on: 27/11/2023
 *      Author: Tiago C. Teixeira
 * Description: Declares the SQL statments.
 */

#ifndef MODELS_SQL_H_
	#define MODELS_SQL_H_

	// Define SQL code
	#define SQLITE_DPCAT_QUERY 	"SELECT * FROM DP_CATEGORIES ORDER BY DP_CAT_NAME;"

	#define SQLITE_DP_QUERY 	"SELECT DP_ID, DP_NAME, DP_CAT_ID, DP_DESC, FREQ_USAGE, \
									FREQ_USAGE_DESC FROM DP LEFT JOIN FREQ_USAGES \
									ON DP.FREQ_USAGE = FREQ_USAGES.LEVEL \
									WHERE DP_CAT_ID = ? ORDER BY DP_NAME;"

	#define SQLITE_CODE_QUERY 	"SELECT DP.DP_ID AS DP_ID1, CODE_ID, CONTENT, \
									CODE.PROG_LANG_ID, PROG_LANG_NAME \
									FROM DP INNER JOIN CODE ON DP.DP_ID = CODE.DP_ID \
									INNER JOIN PROG_LANG ON CODE.PROG_LANG_ID = PROG_LANG.PROG_LANG_ID \
									WHERE (DP.DP_ID = ?);"

	#define SQLITE_PARTICIPANTS_QUERY "SELECT DP_PART_ID, DP_PART_NAME, DP_PART_DESC, \
										DP_ID FROM DP_PART WHERE DP_ID = ? ORDER BY DP_PART_ID;"

	#define SQLITE_USAGE_CASES_QUERY "SELECT DP_UCASE_ID, DP_UCASE_DESIG, DP_UCASE_DESC, \
										DP_ID FROM DP_USAGE_CASES WHERE DP_ID = ? ORDER BY DP_UCASE_DESIG;"



#endif /* MODELS_SQL_H_ */
